### ISSUE TITLE
Group the buttons

### ISSUE THREAD

**Issue by WheresAlice** [geeksforsocialchange/meeting-mood#2]
group the buttons:

- Consent: agree, agree and volunteer, veto, probably needs stand aside and undecided in there too
- Requests: speak up, slow down, I'm confused
- Responses: technical point, direct response

**Comment by kimadactyl** [comment]
I think these need to have different functionality the more I think about it.

Consent is more of an ongoing thing. It starts on "undecided" with each new agenda point and then people can toggle through the others. 

Requests are more like little flags that would pop up -- possibly anonymously? 

Responses are more like requests to go next in the speaking order. Maybe it would be good to implement a "stacker" -- a queue of people wanting to speak. However, in the short term this could basically be a non-anonymous request popup thing?

**Comment by WheresAlice** [comment]
Alright, let's split this into two issues then.  An initial grouping of the buttons with no functional change, and a bigger ticket to add all the extra functionality to treat button types differently.

**Comment by kimadactyl** [comment]
Sounds good!

**Comment by WheresAlice** [comment]
resolved in release v0.3.0
